version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27037:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=test

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8086:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb

volumes:
  mongodb_data: